[package]
name = "substrate-zainium"
version = "1.0.0"
edition = "2021"
description = "Standalone package builder/verifier — pack, unpack, verify, inspect"
license = "MIT"
authors = ["Ali Zain <alizain@zainiumdynamics.tech>"]
repository = "https://gitlab.com/alizain.arch/substrate"
homepage = "https://gitlab.com/alizain.arch/substrate"
readme = "README.md"

[[bin]]
name = "substrate"
path = "src/main.rs"

[dependencies]
clap          = { version = "4",    features = ["derive"] }
serde         = { version = "1",    features = ["derive"] }
serde_json    = "1"
toml          = "0.8"
tar           = "0.4"
zexc          = { version = "1.2.1", default-features = false, features = ["std", "simd"] }
walkdir       = "2"
ed25519-dalek = { version = "2",    features = ["rand_core"] }
rand          = "0.8"
blake3        = "1"
regex         = "1"
hex           = "0.4"
thiserror     = "1"
log           = "0.4"
env_logger    = "0.11"
chrono        = { version = "0.4",  features = ["serde"] }
sha2 = "0.11.0"
oxipatch      = "0.1.0"

[profile.release]
opt-level = 3
lto = true
