//! receipt.rs — Write install receipt .toml alongside the packed .zex.
//!
//! The receipt is what `zex remove` reads to clean up a package.
//! It is also written by the install driver after a successful install.
//! `substrate pack` generates it as a companion file for submission.

use crate::core::manifest::ZexTomlManifest;
use crate::error::Result;
use std::path::Path;

/// Generate and write `<name>-<version>.receipt.toml` next to the .zex.
///
/// The receipt lists every file that would be installed, so the
/// repository maintainer can review the install footprint before approving.
pub fn write_receipt(
    output_path: &Path,
    manifest: &ZexTomlManifest,
    payload_files: &[(String, Vec<u8>)],
    install_root: &str,
) -> Result<std::path::PathBuf> {
    // Map each payload file to its on-disk destination
    let mut installed_files: Vec<String> = Vec::new();
    let _installed_symlinks: Vec<String> = Vec::new();
    let mut installed_dirs: std::collections::HashSet<String> = std::collections::HashSet::new();

    for (rel_path, _bytes) in payload_files {
        // rel_path = "payload/bin/myapp" or "payload/lib/foo.so"
        let stripped = rel_path.strip_prefix("payload/").unwrap_or(rel_path);

        // Find the first path component to map via install paths
        let first_comp = stripped.split('/').next().unwrap_or("");

        let dest_root = manifest.install.paths.get(first_comp)
            .cloned()
            .unwrap_or_else(|| {
                // Default mapping: payload/<subdir> → <install_root>/union/<subdir>
                format!("{}/union/{}", install_root.trim_end_matches('/'), first_comp)
            });

        // e.g. payload/bin/myapp → /overlayer/zexlib/union/bin/myapp
        let filename = stripped.strip_prefix(&format!("{first_comp}/"))
            .unwrap_or(stripped);
        let abs_dest = format!("{}/{}", dest_root.trim_end_matches('/'), filename);

        // Track parent dir
        if let Some(parent) = std::path::Path::new(&abs_dest).parent() {
            installed_dirs.insert(parent.to_string_lossy().to_string());
        }

        installed_files.push(abs_dest);
    }

    // Sort for determinism
    installed_files.sort();
    let mut installed_dirs: Vec<String> = installed_dirs.into_iter().collect();
    installed_dirs.sort();
    installed_dirs.retain(|d| d.starts_with("/overlayer/"));

    // Merge with manifest.remove if already provided
    let final_files = if !manifest.remove.files.is_empty() {
        manifest.remove.files.clone()
    } else {
        installed_files
    };

    let receipt_content = format!(
        r#"# Install receipt — generated by substrate pack
# This file is the ground truth for `zex remove`.
# All paths MUST begin with /overlayer/.

name = {name:?}
version = {version:?}
description = {desc:?}
origin = "tier1-zainium"
installed_at = {now:?}
libc_target = {libc:?}
build_type = {btype:?}
license = {license:?}
maintainer = {maintainer:?}

[remove]
files    = {files:?}
symlinks = {symlinks:?}
dirs     = {dirs:?}
"#,
        name       = manifest.package.name,
        version    = manifest.package.version,
        desc       = manifest.package.description,
        now        = chrono::Utc::now().to_rfc3339(),
        libc       = manifest.package.libc_target.as_deref().unwrap_or("musl"),
        btype      = manifest.package.build_type.as_deref().unwrap_or("dynamic"),
        license    = manifest.package.license,
        maintainer = manifest.package.maintainer,
        files      = final_files,
        symlinks   = manifest.remove.symlinks,
        dirs       = installed_dirs,
    );

    let receipt_path = output_path.with_extension("receipt.toml");
    std::fs::write(&receipt_path, receipt_content)
        .map_err(crate::error::ZexError::Io)?;

    Ok(receipt_path)
}
